package me.osbourn.stealthplugin.settings;

import me.osbourn.stealthplugin.util.NullableBlockPosition;

public final class Settings {
    private Settings() {
    }

    @Setting(name = "timePerRound")
    public static int timePerRound = 300;
    @Setting(name = "prepTime")
    public static int prepTime = 30;
    @Setting(name = "displayGameTargetsOnScoreboard")
    public static boolean displayGameTargetsOnScoreboard = true;
    @Setting(name = "displayTeamsOnScoreboard")
    public static boolean displayTeamsOnScoreboard = false;
    @Setting(name = "displayPlayerNamesOnScoreboard")
    public static boolean displayPlayerNamesOnScoreboard = true;
    @Setting(name = "displayTimeOnScoreboard")
    public static boolean displayTimeOnScoreboard = true;
    @Setting(name = "displayScoreOnScoreboard")
    public static boolean displayScoreOnScoreboard = false;
    @Setting(name = "applyInvisibilityOnStart")
    public static boolean applyInvisibilityOnStart = false;
    @Setting(name = "attackingTeamName")
    public static String attackingTeamName = "red";
    @Setting(name = "defendingTeamName")
    public static String defendingTeamName = "blue";
    @Setting(name = "attackingTeamSpawnLocation")
    public static NullableBlockPosition attackingTeamSpawnLocation = NullableBlockPosition.fromCoords(-17, 51, 67);
    @Setting(name = "defendingTeamSpawnLocation")
    public static NullableBlockPosition defendingTeamSpawnLocation = NullableBlockPosition.fromCoords(-67, 51, 69);
    @Setting(name = "attackingTeamChestLocation")
    public static NullableBlockPosition attackingTeamChestLocation = NullableBlockPosition.UNSET;
    @Setting(name = "defendingTeamChestLocation")
    public static NullableBlockPosition defendingTeamChestLocation = NullableBlockPosition.UNSET;
    @Setting(name = "respawnLocation")
    public static NullableBlockPosition respawnLocation = NullableBlockPosition.fromCoords(-95, 51, 100);
    @Setting(name = "lobbyLocation")
    public static NullableBlockPosition lobbyLocation = NullableBlockPosition.fromCoords(-44, 137, -86);
    @Setting(name = "numberOfTargets")
    public static int numberOfTargets = 2;
    @Setting(name = "morphedPlayersCanAttack")
    public static boolean morphedPlayersCanAttack = false;
    @Setting(name = "morphedPlayersIgnoreArrows")
    public static boolean morphedPlayersIgnoreArrows = true;
    @Setting(name = "mapPasteFile")
    public static String mapPasteFile = "internal/map.schem";
    @Setting(name = "mapPasteLocation")
    public static NullableBlockPosition mapPasteLocation = NullableBlockPosition.fromCoords(0, 50, 0);
    @Setting(name = "lobbyPasteFile")
    public static String lobbyPasteFile = "internal/lobby.schem";
    @Setting(name = "lobbyPasteLocation")
    public static NullableBlockPosition lobbyPasteLocation = NullableBlockPosition.fromCoords(-44, 136, -86);
    @Setting(name = "killEntitiesBeforePaste")
    public static boolean killEntitiesBeforePaste = true;
    @Setting(name = "killArrows")
    public static boolean killArrows = true;
    @Setting(name = "clearInventoryOnDeath")
    public static boolean clearInventoryOnDeath = true;
    @Setting(name = "protectedLayerEnabled")
    public static boolean protectedLayerEnabled = true;
    @Setting(name = "protectedLayerLevel")
    public static int protectedLayerLevel = 50;
    @Setting(name = "disableEnderChests")
    public static boolean disableEnderChests = true;
    @Setting(name = "disableHunger")
    public static boolean disableHunger = true;
    @Setting(name = "preventRemovingArmor")
    public static boolean preventRemovingArmor = true;
    @Setting(name = "increaseEnvironmentalDamage")
    public static boolean increaseEnvironmentalDamage = true;
    @Setting(name = "environmentalDamagePercentIncrease")
    public static int environmentalDamagePercentIncrease = 100;
    @Setting(name = "beaconsRevealPlayers")
    public static boolean beaconsRevealPlayers = true;
    @Setting(name = "morphOnRespawn")
    public static boolean morphOnRespawn = true;
    @Setting(name = "disableMorphedPlayerDeathMessages")
    public static boolean disableMorphedPlayerDeathMessages = false;
    @Setting(name = "playersDropArrows")
    public static boolean playersDropArrows = true;
    @Setting(name = "announceBrokenTargets")
    public static boolean announceBrokenTargets = true;
    @Setting(name = "enforcePrepTime")
    public static boolean enforcePrepTime = true;
    @Setting(name = "preventPrematureTargetDestruction")
    public static boolean preventPrematureTargetDestruction = true;
    @Setting(name = "glowingTeammates")
    public static boolean glowingTeammates = false;
    @Setting(name = "timeInLobby")
    public static int timeInLobby = 30;
    @Setting(name = "explosiveArrows")
    public static boolean explosiveArrows = true;
    @Setting(name = "igniteCocktails")
    public static boolean igniteCocktails = true;
    @Setting(name = "portalSystemEnabled")
    public static boolean portalSystemEnabled = true;
    @Setting(name = "walkieTalkie")
    public static boolean walkieTalkie = true;
}
