name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v3.12.0
        with:
          distribution: temurin
          java-version: 17
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1
      - name: Setup and execute Gradle 'test' task
        uses: gradle/gradle-build-action@v2.7.0
        with:
          gradle-version: 7.3.3
          arguments: test
