name: publish
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v3.12.0
        with:
          distribution: temurin
          java-version: 17
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1
      - name: Setup and execute Gradle 'build' task
        uses: gradle/gradle-build-action@v2.7.0
        with:
          gradle-version: 7.3.3
          arguments: build
      - name: Setup and execute Gradle 'test' task
        uses: gradle/gradle-build-action@v2.7.0
        with:
          gradle-version: 7.3.3
          arguments: test
      - name: Publish
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
